name: Docker Image CI

on:
  workflow_dispatch
  push:
    branches: [ main, cicd-testing ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker-compose build laravel.test
        docker push ghcr.io/csci-2479/test-app:latest
